### ISSUE TITLE
RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used

### ISSUE THREAD

**Issue by drmikecooke** [humenda/GladTeX#18] opened 2023-02-28 13:28 UTC
Lots of these warnings. Tried submitting it with stdbuf -i0 -o0 -e0, but no change in behavior.

This seems to be an issue with python >=3.8. I am on 3.9 (or 3.11 if I feel like it).

I installed it on a raspberry pi bullseye gui (probably runs apt in bg), which may be relevant (and outdated). Maybe a pipx install would be better?

**Comment by humenda** [comment] 2023-02-28 13:38
>Lots of these warnings. Tried submitting it with stdbuf -i0 -o0 -e0, but no change in behavior.

It's already fixed on master, but not yet released. I couldn't get it ready
for bookworm, though.
If required, I could probably do a backport for bookworm.

**Comment by humenda** [comment] 2023-03-19 14:35
I haven't received any comment. Because the issue is fixed on master, I'm
closing the issue. Please reopen if there needs to be something done.

**Closed** 2023-03-19 14:36 UTC
